export const MOCK_SUGGESTIONS = {
  escola: [
    {
      id: 1,
      name: "Período de provas",
      intro_text: "É compreensível se sentir pressionada em períodos de prova.",
      closing_text: "Estudar com qualidade é mais importante do que estudar por horas.",
      suggestions: [
        { id: 1, text: "Divida o conteúdo em partes menores" },
        { id: 2, text: "Use ciclos de estudo (25min + pausa)" },
        { id: 3, text: "Revise ao invés de começar do zero" },
        { id: 4, text: "Priorize o mais importante" },
      ],
    },
    {
      id: 2,
      name: "Acúmulo de atividades",
      intro_text: "Quando muitas tarefas se acumulam, é natural se sentir sobrecarregada.",
      closing_text: null,
      suggestions: [
        { id: 5, text: "Liste tudo que precisa fazer" },
        { id: 6, text: "Comece pela tarefa mais simples" },
        { id: 7, text: "Faça uma coisa de cada vez" },
        { id: 8, text: "Evite multitarefa" },
      ],
    },
    {
      id: 3,
      name: "Dificuldade no conteúdo",
      intro_text: "Nem sempre aprender é linear — isso faz parte do processo.",
      closing_text: null,
      suggestions: [
        { id: 9, text: "Procure vídeos ou explicações diferentes" },
        { id: 10, text: "Estude em blocos curtos" },
        { id: 11, text: "Revise com frequência" },
        { id: 12, text: "Peça ajuda quando possível" },
      ],
    },
    {
      id: 4,
      name: "Pressão por desempenho",
      intro_text: "Sentir pressão pode ser pesado, principalmente com expectativas.",
      closing_text: null,
      suggestions: [
        { id: 13, text: "Foque no seu progresso" },
        { id: 14, text: "Compare-se com você mesma" },
        { id: 15, text: "Defina metas pequenas" },
        { id: 16, text: "Errar faz parte" },
      ],
    },
  ],

  trabalho: [
    {
      id: 10,
      name: "Excesso de demandas",
      intro_text: "Muitas tarefas podem causar cansaço mental.",
      closing_text: null,
      suggestions: [
        { id: 1, text: "Priorize tarefas" },
        { id: 2, text: "Divida atividades grandes" },
        { id: 3, text: "Faça pausas curtas" },
        { id: 4, text: "Organize seu dia" },
      ],
    },
    {
      id: 11,
      name: "Pressão por resultados",
      intro_text: "A cobrança constante pode gerar ansiedade.",
      closing_text: null,
      suggestions: [
        { id: 5, text: "Foque no que está sob seu controle" },
        { id: 6, text: "Estabeleça metas realistas" },
        { id: 7, text: "Evite perfeccionismo" },
        { id: 8, text: "Reconheça seus esforços" },
      ],
    },
    {
      id: 12,
      name: "Conflito com colegas",
      intro_text: "Relações difíceis impactam o emocional.",
      closing_text: null,
      suggestions: [
        { id: 9, text: "Evite reagir no impulso" },
        { id: 10, text: "Busque comunicação clara" },
        { id: 11, text: "Evite conflitos desnecessários" },
        { id: 12, text: "Foque no profissional" },
      ],
    },
    {
      id: 13,
      name: "Falta de reconhecimento",
      intro_text: "Não ser reconhecida pode gerar frustração.",
      closing_text: "Você tem valor, mesmo quando não é reconhecido.",
      suggestions: [
        { id: 13, text: "Valorize seu progresso" },
        { id: 14, text: "Registre conquistas" },
        { id: 15, text: "Busque feedback" },
        { id: 16, text: "Reforce sua autoestima" },
      ],
    },
  ],

  familia: [
    {
      id: 20,
      name: "Discussões",
      intro_text: "Conflitos familiares podem ser desgastantes.",
      closing_text: null,
      suggestions: [
        { id: 1, text: "Evite discutir no calor do momento" },
        { id: 2, text: "Dê um tempo" },
        { id: 3, text: "Ouça o outro lado" },
        { id: 4, text: "Preserve sua energia" },
      ],
    },
    {
      id: 21,
      name: "Falta de apoio",
      intro_text: "Sentir falta de apoio gera solidão.",
      closing_text: null,
      suggestions: [
        { id: 5, text: "Busque apoio em outras pessoas" },
        { id: 6, text: "Expresse seus sentimentos" },
        { id: 7, text: "Valorize quem te apoia" },
        { id: 8, text: "Cuide de você" },
      ],
    },
    {
      id: 22,
      name: "Cobranças",
      intro_text: "Cobranças podem gerar pressão emocional.",
      closing_text: null,
      suggestions: [
        { id: 9, text: "Estabeleça limites" },
        { id: 10, text: "Não absorva tudo" },
        { id: 11, text: "Reforce sua autonomia" },
        { id: 12, text: "Foque no que controla" },
      ],
    },
    {
      id: 23,
      name: "Preocupação com alguém",
      intro_text: "Se preocupar é natural.",
      closing_text: null,
      suggestions: [
        { id: 13, text: "Foque no que pode controlar" },
        { id: 14, text: "Evite antecipar problemas" },
        { id: 15, text: "Respire fundo" },
        { id: 16, text: "Cuide de você também" },
      ],
    },
  ],

  saude: [
    {
      id: 60,
      name: "Sintomas físicos",
      intro_text: "Sentir algo no corpo pode gerar preocupação.",
      closing_text: null,
      suggestions: [
        { id: 1, text: "Evite autodiagnóstico" },
        { id: 2, text: "Procure orientação médica" },
        { id: 3, text: "Observe sem pânico" },
        { id: 4, text: "Descanse" },
      ],
    },
    {
      id: 61,
      name: "Preocupação com diagnóstico",
      intro_text: "A incerteza pode gerar ansiedade.",
      closing_text: null,
      suggestions: [
        { id: 5, text: "Busque fontes confiáveis" },
        { id: 6, text: "Evite excesso de pesquisa" },
        { id: 7, text: "Respire" },
        { id: 8, text: "Foque no presente" },
      ],
    },
    {
      id: 62,
      name: "Falta de energia",
      intro_text: "Cansaço impacta tudo.",
      closing_text: null,
      suggestions: [
        { id: 9, text: "Respeite seus limites" },
        { id: 10, text: "Priorize descanso" },
        { id: 11, text: "Faça pausas" },
        { id: 12, text: "Evite sobrecarga" },
      ],
    },
    {
      id: 63,
      name: "Ansiedade com saúde",
      intro_text: "A preocupação pode amplificar sintomas.",
      closing_text: null,
      suggestions: [
        { id: 13, text: "Pratique respiração" },
        { id: 14, text: "Evite pensamentos catastróficos" },
        { id: 15, text: "Foque no presente" },
        { id: 16, text: "Busque ajuda se necessário" },
      ],
    },
  ],
  transito: [
  {
    id: 30,
    name: "Atraso",
    intro_text: "A sensação de estar atrasada pode gerar ansiedade.",
    closing_text: null,
    suggestions: [
      { id: 1, text: "Aceite o que não pode controlar" },
      { id: 2, text: "Avise se possível" },
      { id: 3, text: "Respire fundo" },
      { id: 4, text: "Foque no próximo passo" },
    ],
  },
  {
    id: 31,
    name: "Trânsito intenso",
    intro_text: "Situações fora do controle geram frustração.",
    closing_text: null,
    suggestions: [
      { id: 5, text: "Ouça algo leve" },
      { id: 6, text: "Evite se irritar" },
      { id: 7, text: "Respire conscientemente" },
      { id: 8, text: "Mantenha a calma" },
    ],
  },
  {
    id: 32,
    name: "Imprevistos",
    intro_text: "Imprevistos fazem parte da rotina.",
    closing_text: null,
    suggestions: [
      { id: 9, text: "Tenha planos alternativos" },
      { id: 10, text: "Seja flexível" },
      { id: 11, text: "Ajuste expectativas" },
      { id: 12, text: "Evite autocobrança" },
    ],
  },
  {
    id: 33,
    name: "Estresse no trajeto",
    intro_text: "O ambiente pode impactar seu humor.",
    closing_text: null,
    suggestions: [
      { id: 13, text: "Ouça música ou podcast" },
      { id: 14, text: "Evite discussões" },
      { id: 15, text: "Pratique respiração" },
      { id: 16, text: "Foque no presente" },
    ],
  },
],
amizades: [
  {
    id: 40,
    name: "Conflito",
    intro_text: "Conflitos podem gerar desconforto emocional.",
    closing_text: null,
    suggestions: [
      { id: 1, text: "Espere antes de reagir" },
      { id: 2, text: "Busque diálogo calmo" },
      { id: 3, text: "Evite suposições" },
      { id: 4, text: "Seja clara" },
    ],
  },
  {
    id: 41,
    name: "Distanciamento",
    intro_text: "O afastamento pode gerar tristeza.",
    closing_text: null,
    suggestions: [
      { id: 5, text: "Reflita sobre retomar contato" },
      { id: 6, text: "Respeite o tempo do outro" },
      { id: 7, text: "Invista em novas conexões" },
      { id: 8, text: "Cuide de você" },
    ],
  },
  {
    id: 42,
    name: "Falta de apoio",
    intro_text: "Nem sempre recebemos o apoio esperado.",
    closing_text: null,
    suggestions: [
      { id: 9, text: "Alinhe expectativas" },
      { id: 10, text: "Busque outras pessoas" },
      { id: 11, text: "Valorize quem está presente" },
      { id: 12, text: "Reforce sua autonomia" },
    ],
  },
  {
    id: 43,
    name: "Rejeição",
    intro_text: "A sensação de rejeição pode ser difícil.",
    closing_text: null,
    suggestions: [
      { id: 13, text: "Não leve tudo para o pessoal" },
      { id: 14, text: "Reforce sua autoestima" },
      { id: 15, text: "Evite generalizações" },
      { id: 16, text: "Lembre do seu valor" },
    ],
  },
],
dinheiro: [
  {
    id: 50,
    name: "Preocupação com contas",
    intro_text: "Preocupações financeiras geram ansiedade.",
    closing_text: null,
    suggestions: [
      { id: 1, text: "Liste suas despesas" },
      { id: 2, text: "Priorize o essencial" },
      { id: 3, text: "Planeje aos poucos" },
      { id: 4, text: "Evite impulsividade" },
    ],
  },
  {
    id: 51,
    name: "Gastos inesperados",
    intro_text: "Imprevistos financeiros são comuns.",
    closing_text: null,
    suggestions: [
      { id: 5, text: "Reorganize o orçamento" },
      { id: 6, text: "Evite culpa" },
      { id: 7, text: "Ajuste prioridades" },
      { id: 8, text: "Planeje reserva" },
    ],
  },
  {
    id: 52,
    name: "Falta de planejamento",
    intro_text: "Sem planejamento, a insegurança aumenta.",
    closing_text: null,
    suggestions: [
      { id: 9, text: "Comece simples" },
      { id: 10, text: "Registre gastos" },
      { id: 11, text: "Defina limites" },
      { id: 12, text: "Revise mensalmente" },
    ],
  },
  {
    id: 53,
    name: "Insegurança financeira",
    intro_text: "Incerteza gera desconforto.",
    closing_text: null,
    suggestions: [
      { id: 13, text: "Foque no presente" },
      { id: 14, text: "Planeje pequenos passos" },
      { id: 15, text: "Evite catastrofizar" },
      { id: 16, text: "Busque informação" },
    ],
  },
],
sono: [
  {
    id: 70,
    name: "Dificuldade para dormir",
    intro_text: "A mente agitada dificulta o descanso.",
    closing_text: null,
    suggestions: [
      { id: 1, text: "Evite telas antes de dormir" },
      { id: 2, text: "Crie rotina" },
      { id: 3, text: "Respire profundamente" },
      { id: 4, text: "Reduza estímulos" },
    ],
  },
  {
    id: 71,
    name: "Sono não reparador",
    intro_text: "Dormir mal afeta o dia.",
    closing_text: null,
    suggestions: [
      { id: 5, text: "Ajuste horários" },
      { id: 6, text: "Evite cafeína" },
      { id: 7, text: "Melhore ambiente" },
      { id: 8, text: "Priorize descanso" },
    ],
  },
  {
    id: 72,
    name: "Pensamentos à noite",
    intro_text: "Pensamentos acelerados atrapalham.",
    closing_text: null,
    suggestions: [
      { id: 9, text: "Anote pensamentos" },
      { id: 10, text: "Respire" },
      { id: 11, text: "Evite resolver tudo agora" },
      { id: 12, text: "Relaxe" },
    ],
  },
  {
    id: 73,
    name: "Rotina desregulada",
    intro_text: "Falta de rotina impacta o sono.",
    closing_text: null,
    suggestions: [
      { id: 13, text: "Crie horários fixos" },
      { id: 14, text: "Evite cochilos longos" },
      { id: 15, text: "Tenha rotina noturna" },
      { id: 16, text: "Seja consistente" },
    ],
  },
],
};